version: "2"

services:
  was:
    image: dev.sangah.com:5043/pmis-tomcat
    extra_hosts:
      - "db:203.239.21.121"
    expose:
      - "8081"
      - "8080"
    volumes:
      - app:/usr/local/tomcat/webapps
      - log:/usr/local/tomcat/logs
      - edms:/edms
  apache:
    build: .
    image: pmis-apache
    ports:
      - "80:80"
      - "443:443"
    links:
      - was:was
    volumes:
      - app:/var/www
      - log:/var/log/apache2
      - ./tls:/etc/pki/tls/app
    environment:
      - APACHE_SSL

volumes:
  log:
  app:
  edms: