version: "2"

services:
  was:
    image: dev.sangah.com:5043/pmis-tomcat
    volumes:
      - app:/usr/local/tomcat/webapps

  httpd:
    build: .
    image: pmis-apache
    ports:
      - "80:80"
      - "443:443"
    links:
      - was:was
    volumes:
      - app:/var/www
      - ${APACHE_SSL_CERT_PATH}:/etc/ssl/app:ro
      #- /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      - APACHE_SSL
      - APACHE_SSL_KEY
      - APACHE_SSL_CERT
      - APACHE_SSL_CHAIN

volumes:
  app: